development: &development
  secret_key_base: e369575030a3ac3c396ccb152187c43e61e03721a910e5a90a1153c0f06b04c2a2b750ffb0020152a6580c261cb86ae11936f0ea2deec6380012b33d35b7fd3c
  facebook_app_secret: 54184e2e7c7e3fdff29faec05233547a
  facebook_app_id: 519942891502567
  fridges_api_url: https://heladera-social.herokuapp.com
  # amazons3_key:
  # amazons3_secret:
  # amazons3_region:
  # amazons3_bucket_name:
test:
  <<: *development

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rollbar_access_token: <%= ENV["ROLLBAR_ACCESS_TOKEN"] %>
  trello_url: <%= ENV["TRELLO_URL"] %>
  email_recipients_interceptors: <%= ENV["EMAIL_RECIPIENTS_INTERCEPTOR"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  fridges_api_url: https://heladera-social.herokuapp.com
  # amazons3_key: <%= ENV["AMAZONS3_KEY"] %>
  # amazons3_secret: <%= ENV["AMAZONS3_SECRET"] %>
  # amazons3_region: <%= ENV["AMAZONS3_REGION"] %>
  # amazons3_bucket_name: <%= ENV["AMAZONS3_BUCKET_NAME"] %>
